spring.application.name=backend_taller

spring.datasource.url=jdbc:mysql://localhost:3306/moto_taller_db
spring.datasource.username=root
spring.datasource.password=sa..

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


server.port=8080

jwt.secret=RrmwbLMhoLP9F+AR1Bjt/iM9IBWeB32J6TrpxpMRcVw=
jwt.expiration=86400000